### PR TITLE
Add login window

### PR DESCRIPTION
**Pull request by michaelpearson**

### CODE REVIEW

**Comment by StephenThompson** [comment]
Do you think typing in the password each time to test a new feature will become kinda annoying?

**Comment by michaelpearson** [comment]
Yeah true. Maybe we could add a flag or something. Ill open another user story for it.

**Comment by michaelpearson** [comment]
Other then that do you think its ready to merge?

**Comment by StephenThompson** [comment]
You could just change the password to "" for both the clerk and manager. That would be an easier solution.

**Comment by michaelpearson** [comment]
Yeah good idea! Ok ill do that.

**Pull request closed without merging**
