### PR TITLE
Initial main window design

### PR DESCRIPTION
**Pull request by michaelpearson**
Main window working pretty well. Still a MVP but its a start.

### CODE REVIEW

**Comment by CDeighton** [comment]
Problem on clicking the add route button after the change of AddRoute class to RouteDialog

**Comment by michaelpearson** [comment]
Ok i've pushed a fix.

**Comment by CDeighton** [comment]
Fix works, ready for merge.

**Comment by michaelpearson** [comment]
:+1: Cheers.

**Pull request merged**
