### PR TITLE
Remove location object

### PR DESCRIPTION
**Pull request by michaelpearson**

### CODE REVIEW

**Comment by michaelpearson** [comment]
@StephenThompson Could you take a look at this?

**Comment by StephenThompson** [comment]
The Test.xml file has some wrong "to" and "from" values. Routes and mail should not have New Zealand as a to or from location, only the customer price events should.

**Comment by michaelpearson** [comment]
Could you fix that up for me. I'm not sure what the actual values should be.

**Comment by StephenThompson** [comment]
Just to make sure I've checked everything, have you refactored the dialogs and removed the location objects?

**Comment by michaelpearson** [comment]
Yup. I've checked all the dialogs work and have removed the location object. 
https://github.com/michaelpearson/SWEN-301-KPS/pull/17/files#diff-e59a53593eb7ab65f2526d3215f22f4bL1

**Pull request merged**
